"""
Type stubs for the _oboron native Rust extension module.

These stubs enable IDE autocompletion (VS Code, PyCharm), mypy, and pyright
support for the oboron Python bindings.
"""

from typing import Optional

__version__: str

# ============================================================================
# Fixed-format codec classes
# ============================================================================

class DgcmsivC32:
    def __init__(self, key: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def key_hex(self) -> str: ...
    @property
    def key_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class DgcmsivB32:
    def __init__(self, key: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def key_hex(self) -> str: ...
    @property
    def key_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class DgcmsivB64:
    def __init__(self, key: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def key_hex(self) -> str: ...
    @property
    def key_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class DgcmsivHex:
    def __init__(self, key: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def key_hex(self) -> str: ...
    @property
    def key_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class DsivC32:
    def __init__(self, key: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def key_hex(self) -> str: ...
    @property
    def key_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class DsivB32:
    def __init__(self, key: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def key_hex(self) -> str: ...
    @property
    def key_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class DsivB64:
    def __init__(self, key: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def key_hex(self) -> str: ...
    @property
    def key_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class DsivHex:
    def __init__(self, key: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def key_hex(self) -> str: ...
    @property
    def key_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class PgcmsivC32:
    def __init__(self, key: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def key_hex(self) -> str: ...
    @property
    def key_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class PgcmsivB32:
    def __init__(self, key: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def key_hex(self) -> str: ...
    @property
    def key_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class PgcmsivB64:
    def __init__(self, key: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def key_hex(self) -> str: ...
    @property
    def key_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class PgcmsivHex:
    def __init__(self, key: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def key_hex(self) -> str: ...
    @property
    def key_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class PsivC32:
    def __init__(self, key: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def key_hex(self) -> str: ...
    @property
    def key_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class PsivB32:
    def __init__(self, key: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def key_hex(self) -> str: ...
    @property
    def key_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class PsivB64:
    def __init__(self, key: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def key_hex(self) -> str: ...
    @property
    def key_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class PsivHex:
    def __init__(self, key: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def key_hex(self) -> str: ...
    @property
    def key_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

# ============================================================================
# Flexible interfaces
# ============================================================================

class Ob:
    def __init__(self, format: str, key: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def key_hex(self) -> str: ...
    @property
    def key_bytes(self) -> bytes: ...
    def set_format(self, format: str) -> None: ...
    def set_scheme(self, scheme: str) -> None: ...
    def set_encoding(self, encoding: str) -> None: ...
    def __repr__(self) -> str: ...

class Omnib:
    def __init__(self, key: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str, format: str) -> str: ...
    def dec(self, obtext: str, format: str) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def key_hex(self) -> str: ...
    @property
    def key_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

# ============================================================================
# Mock/testing codec classes
# ============================================================================

class Mock1C32:
    def __init__(self, key: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def key_hex(self) -> str: ...
    @property
    def key_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class Mock1B32:
    def __init__(self, key: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def key_hex(self) -> str: ...
    @property
    def key_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class Mock1B64:
    def __init__(self, key: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def key_hex(self) -> str: ...
    @property
    def key_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class Mock1Hex:
    def __init__(self, key: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def key_hex(self) -> str: ...
    @property
    def key_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class Mock2C32:
    def __init__(self, key: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def key_hex(self) -> str: ...
    @property
    def key_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class Mock2B32:
    def __init__(self, key: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def key_hex(self) -> str: ...
    @property
    def key_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class Mock2B64:
    def __init__(self, key: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def key_hex(self) -> str: ...
    @property
    def key_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

class Mock2Hex:
    def __init__(self, key: Optional[str] = None, keyless: bool = False) -> None: ...
    def enc(self, plaintext: str) -> str: ...
    def dec(self, obtext: str) -> str: ...
    @property
    def format(self) -> str: ...
    @property
    def scheme(self) -> str: ...
    @property
    def encoding(self) -> str: ...
    @property
    def key(self) -> str: ...
    @property
    def key_hex(self) -> str: ...
    @property
    def key_bytes(self) -> bytes: ...
    def __repr__(self) -> str: ...

# ============================================================================
# Key generation functions
# ============================================================================

def generate_key() -> str: ...
def generate_key_bytes() -> bytes: ...

# ============================================================================
# Convenience functions
# ============================================================================

def enc(plaintext: str, format: str, key: str) -> str: ...
def enc_keyless(plaintext: str, format: str) -> str: ...
def dec(obtext: str, format: str, key: str) -> str: ...
def dec_keyless(obtext: str, format: str) -> str: ...

# ============================================================================
# Exception hierarchy
# ============================================================================

class OboronError(Exception):
    """Base class for all oboron exceptions."""
    ...

class InvalidKey(OboronError):
    """Bad hex / wrong-length key."""
    ...

class InvalidFormat(OboronError):
    """Unknown scheme / encoding / malformed format string."""
    ...

class EncryptionFailed(OboronError):
    """AEAD failure / empty plaintext."""
    ...

class DecryptionFailed(OboronError):
    """Tag check, obtext-decode, or post-decrypt UTF-8 validation failure."""
    ...
