"""Z-tier codecs (obfuscation only — NOT cryptographically secure).

The z-tier schemes (``zrbcx``, ``legacy``, and the testing ``zmock1``)
use a 32-byte secret instead of the a/u-tier 64-byte master key. They
share the same string-in/string-out interface as the rest of oboron,
but they exist for obfuscation, not security.

Quick start::

    from oboron import generate_secret
    from oboron.ztier import ZrbcxC32

    secret = generate_secret()           # 64-char hex
    z = ZrbcxC32(secret)
    obtext = z.enc("hello")
    plaintext = z.dec(obtext)

The z-tier core ``new()`` accepts the 43-character base64 secret form;
the hex form is also generated by ``generate_secret()`` and can be
converted as needed. Both round-trip via ``.secret`` (base64) and
``.secret_hex`` (hex).
"""

from abc import ABC, abstractmethod

from . import _oboron


class ZtierBase(ABC):
    """Abstract base class for all z-tier codec implementations.

    All z-tier classes (``ZrbcxC32``, ``ZrbcxB32``, …, ``Legacy``,
    ``Zmock1*``) plus the flexible ``Obz`` are registered as virtual
    subclasses, enabling ``isinstance()`` / ``issubclass()`` checks.
    """

    @abstractmethod
    def enc(self, plaintext: str) -> str: ...

    @abstractmethod
    def dec(self, obtext: str) -> str: ...

    @property
    @abstractmethod
    def format(self) -> str: ...

    @property
    @abstractmethod
    def scheme(self) -> str: ...

    @property
    @abstractmethod
    def encoding(self) -> str: ...

    @property
    @abstractmethod
    def secret(self) -> str:
        """The 43-character base64 secret bound to this codec."""
        ...

    @property
    @abstractmethod
    def secret_hex(self) -> str:
        """The 64-character hex form of the secret."""
        ...

    @property
    @abstractmethod
    def secret_bytes(self) -> bytes:
        """The raw 32-byte secret material."""
        ...


# ============================================================================
# Register Rust classes as virtual subclasses
# ============================================================================


def _register_if_present(*names: str) -> None:
    for name in names:
        cls = getattr(_oboron, name, None)
        if cls is not None:
            ZtierBase.register(cls)


_register_if_present(
    "ZrbcxC32", "ZrbcxB32", "ZrbcxB64", "ZrbcxHex",
    "Legacy",
    "Zmock1C32", "Zmock1B32", "Zmock1B64", "Zmock1Hex",
    "Obz",
)


# ============================================================================
# Re-exports
# ============================================================================

Obz = getattr(_oboron, "Obz", None)
Omnibz = getattr(_oboron, "Omnibz", None)

# Zrbcx
ZrbcxC32 = getattr(_oboron, "ZrbcxC32", None)
ZrbcxB32 = getattr(_oboron, "ZrbcxB32", None)
ZrbcxB64 = getattr(_oboron, "ZrbcxB64", None)
ZrbcxHex = getattr(_oboron, "ZrbcxHex", None)

# Legacy
Legacy = getattr(_oboron, "Legacy", None)

# Zmock1 (testing)
Zmock1C32 = getattr(_oboron, "Zmock1C32", None)
Zmock1B32 = getattr(_oboron, "Zmock1B32", None)
Zmock1B64 = getattr(_oboron, "Zmock1B64", None)
Zmock1Hex = getattr(_oboron, "Zmock1Hex", None)

# Utility functions (re-exported here for ergonomics — the canonical
# import path is `from oboron import generate_secret`).
generate_secret = _oboron.generate_secret
generate_secret_bytes = _oboron.generate_secret_bytes


__all__ = [
    "ZtierBase",
    "Obz",
    "Omnibz",
    "ZrbcxC32", "ZrbcxB32", "ZrbcxB64", "ZrbcxHex",
    "Legacy",
    "Zmock1C32", "Zmock1B32", "Zmock1B64", "Zmock1Hex",
    "generate_secret",
    "generate_secret_bytes",
]
